version: '3'
services:

  #PHP Service
  app:
    container_name: hms-app
    image: hms-app-image
    build:
      context: .
      dockerfile: docker/Dockerfile-php8
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    extra_hosts:
      - "host.docker.internal:192.168.1.107"
      - "api.hms-dev.io:192.168.1.107"
    networks:
      - hms-network

  #Nginx Service
  nginx:
    container_name: hms-nginx
    image: nginx:1.17
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "host.docker.internal:192.168.1.107"
      - "api.hms-dev.io:192.168.1.107"
    networks:
      - hms-network

  #MySQL Service
  database:
    container_name: hms-mysql
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3307"
    command: [
      "mysqld",
      "--default-authentication-plugin=mysql_native_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    environment:
      MYSQL_DATABASE: hms_local_db
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker/database_data_dir:/var/lib/mysql
    extra_hosts:
      - "host.docker.internal:192.168.1.107"
      - "api.hms-dev.io:192.168.1.107"
    networks:
      - hms-network

#Docker Networks
networks:
  hms-network:
    driver: bridge